# Generated by Django 2.1.2 on 2019-01-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=144)),
                ('image_heigth', models.IntegerField()),
                ('image_width', models.IntegerField()),
                ('image', models.ImageField(height_field=models.IntegerField(), upload_to='media/%Y/%m/%d/', width_field=models.IntegerField())),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
