# Generated by Django 2.1.5 on 2019-01-06 04:45

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20190106_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=image_cropping.fields.ImageCropField(upload_to='%Y/%m/%d/'),
        ),
    ]
