# Generated by Django 2.1.2 on 2019-01-06 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20190106_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='image_heigth',
        ),
        migrations.AddField(
            model_name='photo',
            name='image_height',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(height_field='image_height', upload_to='%Y/%m/%d/', width_field='image_width'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image_width',
            field=models.FloatField(),
        ),
    ]
